#define                 MAX_ACCOUNT_PASSWORD                    60
#define                 MAX_EMAIL_LENGTH                        75

#define                 MIN_CHARACTER_YEAR                      1926
#define                 MAX_CHARACTER_YEAR                      2021

#define                 MAX_CHAT_STRING                         80  
#define                 MAX_CHARACTER_ACCENT                    24
#define                 MAX_CHARACTER_DESCRIBE                  128

#define                 MAX_DOOR_NAME                           30
#define                 MAX_DOOR_PRICE                          99999999